export const CALENDAR_LIST_REQUEST = "CALENDAR_LIST_REQUEST";
export const CALENDAR_LIST_SUCCESS = "CALENDAR_LIST_SUCCESS";
export const CALENDAR_LIST_FAIL = "CALENDAR_LIST_FAIL";

export const CALENDAR_CREATE_REQUEST = "CALENDAR_CREATE_REQUEST";
export const CALENDAR_CREATE_SUCCESS = "CALENDAR_CREATE_SUCCESS";
export const CALENDAR_CREATE_FAIL = "CALENDAR_CREATE_FAIL";

export const CALENDAR_UPDATE_REQUEST = "CALENDAR_UPDATE_REQUEST";
export const CALENDAR_UPDATE_SUCCESS = "CALENDAR_UPDATE_SUCCESS";
export const CALENDAR_UPDATE_FAIL = "CALENDAR_UPDATE_FAIL";

export const CALENDAR_DELETE_REQUEST = "CALENDAR_DELETE_REQUEST";
export const CALENDAR_DELETE_SUCCESS = "CALENDAR_DELETE_SUCCESS";
export const CALENDAR_DELETE_FAIL = "CALENDAR_DELETE_FAIL";
