// src/redux/constants/workspaceConstants.js
export const WORKSPACE_LIST_REQUEST = 'WORKSPACE_LIST_REQUEST';
export const WORKSPACE_LIST_SUCCESS = 'WORKSPACE_LIST_SUCCESS';
export const WORKSPACE_LIST_FAIL = 'WORKSPACE_LIST_FAIL';

export const WORKSPACE_CREATE_REQUEST = 'WORKSPACE_CREATE_REQUEST';
export const WORKSPACE_CREATE_SUCCESS = 'WORKSPACE_CREATE_SUCCESS';
export const WORKSPACE_CREATE_FAIL = 'WORKSPACE_CREATE_FAIL';

export const WORKSPACE_USER_ROLE_REQUEST = 'WORKSPACE_USER_ROLE_REQUEST';
export const WORKSPACE_USER_ROLE_SUCCESS = 'WORKSPACE_USER_ROLE_SUCCESS';
export const WORKSPACE_USER_ROLE_FAIL = 'WORKSPACE_USER_ROLE_FAIL';
